export const projects = [
  {
    title: 'FOOD Munch App',
    description: "This is a project that was built to solve food ordering problems. This is a web-based application that gives clients a plethora of options when seeking for cooked food product and service.",
      image: '/images/1.png',
      tags: [ 'NodeJS', 'Express', 'Typescript', 'React', 'PostgreSQL'],
    source: 'https://foodorderring.netlify.app/',
    visit: 'https://foodorderring.netlify.app/',
    id: 0,
  },
  {
    title: 'ILEARN',
    description:"This is a learning app, that connects students with tutor for a one on one class.",
    image: '/images/2.png',
    tags: ['React', 'TypeScript', 'NodeJS', 'Express', 'PostgreSQL'],
    source: 'https://ilearn-sq012-node.netlify.app/',
    visit: 'https://ilearn-sq012-node.netlify.app/',
    id: 1,
  },
  {
    title: 'Court App',
    description: "This is a project that was built to ease the work flow of a court.",
      image: '/images/3.png',
      tags: ['React', 'TypeScript', ],
    source: 'rvs-family-court-staging.netlify.app',
    visit: 'rvs-family-court-staging.netlify.app',
    id: 2,
  },
  {
    title: 'Star Wars',
    description: "A single page application (SPA) that displays all characters of the Star Wars Movie. Built with vanilla JavaScript, JQuery,HTML5 and CSS3.",
    image: '/images/4.jpg',
    tags: [' HTML5, CSS3, JavaScript, JQuery'],
    source: ' https://tobbiestarwars.netlify.app/ ',
    visit: ' https://tobbiestarwars.netlify.app/',
    id: 3,
  },
  {
    title: 'E-Commerce',
    description: "This is an application that enables users to buy and sell products and services online. It typically includes features such as product catalogs, shopping carts, payment gateways, order tracking, and customer support. ",
    image: '/images/5.png',
    tags: ['React', 'NodeJS', 'Express', 'MongoDB'],
    source: ' https://tobbiestarwars.netlify.app/ ',
    visit: ' https://tobbiestarwars.netlify.app/',
    id: 4,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey', },
  { year: 2018, text: 'Worked as a freelance developer', },
  { year: 2019, text: 'Founded JavaScript Mastery', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];